# Lecture 9: Functions #

In [2]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Defining Functions ##

Example: Create a function that takes a numerical input and triples it: $\textsf{triple}(x)=3\,x$

In [3]:
def triple(x):
    return 3 * x

In [4]:
triple(4)

12

We can also assign a value to a name, and call the function on the name:

In [5]:
num = 4

In [6]:
triple(num)

12

## The Anatomy of a Function ##  
    
```python
def functionname(Arguments_Parameters_Expressions_or_Values):     
      return return_expression
```

## Functions are Type-Agnostic  ##

In [7]:
triple('ha')

'hahaha'

In [8]:
triple(np.arange(4))

array([0, 3, 6, 9])

### Discussion ###

- What does the following function do?
- What type of input does it take?
- What type of output does it produce?
- What's a good name for the function?

```python
def f(s):     
      return np.round(s / sum(s) * 100, 2)
```

In [9]:
def percent_of_total(s):
    return np.round(s / sum(s) * 100, 2)

In [10]:
first_four=make_array(1,2,3,4)
first_four

array([1, 2, 3, 4])

In [11]:
percent_of_total(first_four)

array([ 10.,  20.,  30.,  40.])

In [12]:
percent_of_total(make_array(1, 213, 38))

array([  0.4 ,  84.52,  15.08])

### Functions Can Take Multiple Arguments ###

Example: Calculate the Hypotenuse Length of a Right Triangle


Pythagoras's Theorem: If $x$ and $y$ denote the lengths of the right-angle sides, then the hypotenuse length $h$ satisfies:

$$ h^2 = x^2 + y^2 \qquad \text{which implies}\qquad \hspace{20 pt} h = \sqrt{ x^2 + y^2 } $$

In [13]:
def hypotenuse(x, y):
    hypot_squared = (x ** 2 + y ** 2)
    hypot = hypot_squared ** 0.5
    return hypot

In [14]:
hypotenuse(1, 2)

2.23606797749979

In [15]:
hypotenuse(3, 4)

5.0

## Apply ##

In [16]:
ages = Table().with_columns(
    'Person', make_array('Jim', 'Pam', 'Michael', 'Creed'),
    'Birth Year', make_array(1985, 1988, 1967, 1904)
)
ages

Person  | Birth Year
Jim     | 1985
Pam     | 1988
Michael | 1967
Creed   | 1904

In [17]:
def name_and_birthyear(name, year):
    return name + " was born in " + str(year) + "."

In [18]:
ages_and_years = ages.apply(name_and_birthyear, 'Person', 'Birth Year')
ages_and_years

array(['Jim was born in 1985.', 'Pam was born in 1988.',
       'Michael was born in 1967.', 'Creed was born in 1904.'],
      dtype='<U25')

In [19]:
ages_and_years[0]

'Jim was born in 1985.'

# Practice

1. Define a function named percent_increase that takes two inputs: small and big. The function returns the the *percent* increase from small to big. For example, if small = 100 and big = 105, then percent_increase(small, big) returns 5.

2. Apply this function to the Gross and Adjusted Gross columns of top_movies.

3. Attach this new column to the table.

In [ ]:
top_movies = Table.read_table('top_movies_2017.csv').select("Title", "Gross", "Gross (Adjusted)")
top_movies

def percent_increse(small,big):
    percent = (big/small - 1) *100
    return percent


percentint = top_movies.apply(percent_increse,'Gross' ,'Gross (Adjusted)' )
topmoviesmore = top_movies.with_columns('percentint',percentint)
topmoviesmore

Title                            | Gross     | Gross (Adjusted) | percentint
Gone with the Wind               | 198676459 | 1796176700       | 804.071
Star Wars                        | 460998007 | 1583483200       | 243.49
The Sound of Music               | 158671368 | 1266072700       | 697.921
E.T.: The Extra-Terrestrial      | 435110554 | 1261085000       | 189.831
Titanic                          | 658672302 | 1204368000       | 82.8478
The Ten Commandments             | 65500000  | 1164590000       | 1678
Jaws                             | 260000000 | 1138620700       | 337.931
Doctor Zhivago                   | 111721910 | 1103564200       | 887.778
The Exorcist                     | 232906145 | 983226600        | 322.156
Snow White and the Seven Dwarves | 184925486 | 969010000        | 424
... (190 rows omitted)

In [23]:
def percent_increse(small,big):
    percent = (big/small - 1) *100
    return percent

percent_increse(100,105)

5.000000000000004