In [17]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

In [18]:
survey = Table.read_table('welcome_survey_sp24.csv')
survey.show(3)

## Pivot Tables

In [19]:
# Create a new table where:
# Columns are all the different values in the "Handedness" column of the original table
# Rows are all the different values in the "Sleep position" column of the original table
# The entry is the number of people who answered that combination of "Handedness" and "Sleep position"
survey.pivot("Handedness", "Sleep position")

Sleep position     | Ambidexterous | Ambidextrous | Cross-dominant | I can write with both but my right hand is much better. | Left-handed | Right-handed | ambidextrous | both
On your back       | 0             | 1            | 1              | 0                                                       | 23          | 220          | 1            | 0
On your left side  | 0             | 0            | 0              | 0                                                       | 24          | 226          | 0            | 1
On your right side | 0             | 0            | 0              | 1                                                       | 14          | 294          | 1            | 0
On your stomach    | 1             | 1            | 0              | 0                                                       | 8           | 115          | 0            | 0

In [20]:
# Similar to the group command, you can specify something to record in the cell other than the count
# This example records the minimum value of "Number of textees" for each of the pivot categories
survey.pivot("Handedness", "Sleep position", "Number of textees", min)

Sleep position     | Ambidexterous | Ambidextrous | Cross-dominant | I can write with both but my right hand is much better. | Left-handed | Right-handed | ambidextrous | both
On your back       | 0             | 15           | 2              | 0                                                       | 0           | 0            | 10           | 0
On your left side  | 0             | 0            | 0              | 0                                                       | 2           | -10          | 0            | 4
On your right side | 0             | 0            | 0              | 8                                                       | 1           | 0            | 10           | 0
On your stomach    | 9             | 7            | 0              | 0                                                       | 2           | 0            | 0            | 0

# Practice

In [21]:
# From the CORGIS Dataset Project
# By Austin Cory Bart acbart@vt.edu
# Version 2.0.0, created 3/22/2016
# https://corgis-edu.github.io/corgis/csv/skyscrapers/

sky = Table.read_table('skyscrapers.csv')
sky.show(3)

1. For each city, find the number of skyscrapers of each type of material.
2. For each city, find the tallest skyscraper of each type of material. (Add a third column and collect function.)

In [22]:
sky.pivot('material','city')
sky.pivot('material','city','height',max)

city       | concrete | mixed/composite | steel
Atlanta    | 264.25   | 311.8           | 169.47
Austin     | 208.15   | 0               | 93.6
Baltimore  | 161.24   | 0               | 155.15
Boston     | 121.92   | 139             | 240.79
Charlotte  | 265.48   | 239.7           | 179.23
Chicago    | 423.22   | 306.94          | 442.14
Cincinnati | 125      | 202.69          | 175
Cleveland  | 125      | 288.65          | 215.8
Columbus   | 79.25    | 0               | 169.3
Dallas     | 176.48   | 280.72          | 270.06
... (25 rows omitted)

## Joins

In [23]:
drinks = Table(['Drink', 'Cafe', 'Price'])
drinks = drinks.with_rows([
    ['Milk Tea', 'Asha', 5.5],
    ['Espresso', 'Strada',  1.75],
    ['Latte',    'Strada',  3.25],
    ['Espresso', "FSM",   2]
])
drinks

Drink    | Cafe   | Price
Milk Tea | Asha   | 5.5
Espresso | Strada | 1.75
Latte    | Strada | 3.25
Espresso | FSM    | 2

In [24]:
discounts = Table().with_columns(
    'Coupon % off', make_array(10, 25, 5),
    'Location', make_array('Asha', 'Strada', 'Asha')
)
discounts

Coupon % off | Location
10           | Asha
25           | Strada
5            | Asha

In [25]:
# In the drinks table, the name of the cafe is in the column 'Cafe'
# In the discounts table, this same name appears in the column 'Location'
# We can join these tables by matching up the entries in these two columns
combined = drinks.join('Cafe', discounts, 'Location')
combined

Cafe   | Drink    | Price | Coupon % off
Asha   | Milk Tea | 5.5   | 10
Asha   | Milk Tea | 5.5   | 5
Strada | Espresso | 1.75  | 25
Strada | Latte    | 3.25  | 25

# Practice
Join the toppings table to the cones table so that the suggested topping appears in each row of cones.

In [26]:
cones = Table.read_table('cones.csv')
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [27]:
toppings = Table(['Ice Cream', 'Topping'])
toppings = toppings.with_rows([
    ['strawberry', 'marshmallow'],
    ['chocolate', 'caramel'],
    ['bubblegum', 'sprinkles']
])
toppings

Ice Cream  | Topping
strawberry | marshmallow
chocolate  | caramel
bubblegum  | sprinkles

In [28]:
c = cones.join('Flavor', toppings, 'Ice Cream')
c

Flavor     | Color       | Price | Topping
bubblegum  | pink        | 4.75  | sprinkles
chocolate  | light brown | 4.75  | caramel
chocolate  | dark brown  | 5.25  | caramel
chocolate  | dark brown  | 5.25  | caramel
strawberry | pink        | 3.55  | marshmallow
strawberry | pink        | 5.25  | marshmallow